Fix getCurrentSpareInstanceCount - check busy nodes in given fleet, not whole Jenkins instance
jenkinsci/ec2-fleet-plugin pull request #343
Opened 2022-08-10 19:07 UTC by h-okon

This fixes #342.
getCurrentSpareInstanceCount checks in whole Jenkins computers and does not account that we want to check only in given fleet. 
I added a filter to filter worker nodes only from given fleet that is being checked. If we are not checking the computer from given fleet - we continue, we don't want to count the computer as busy computer in given fleet, **because it is not a part of given fleet**.

2022-08-16 12:29 UTC, h-okon commented
@haugenj @imuqtadir Is there a possibility to kindly ask for a review please?

2022-08-16 16:11 UTC, brycahta commented
@h-okon , thanks for both opening the issue and following up with a fix. I'll review this today.

> @haugenj @imuqtadir Is there a possibility to kindly ask for a review please?

Unfortunately (for us), those guys are no longer with the team

2022-08-16 20:04 UTC, brycahta requested changes
Makes sense to me. Could you just add a comment to the added code with your explanation?

2022-08-16 20:14 UTC, h-okon commented
I have added a comment explaining the code

2022-08-16 20:15 UTC, brycahta approved these changes
/lgtm

Apologies for any delays getting this merged, we are in the process of transferring some permissions.

2022-08-17 08:29 UTC, mwos-sl commented
Can we have a new release after this one is merged? I think we observed the same and would love to apply the fix asap.

2022-08-18 19:32 UTC, merged