clarify Always Reconnect property of EC2 Fleet cloud configurations
jenkinsci/ec2-fleet-plugin pull request #394
Opened 2023-08-04 16:49 UTC by vineeth-bandi

Issue: #349 
Clarifying the Always Reconnect property of EC2 Fleet cloud configurations based on #349 on Jenkins UI.
### Testing done
Created two cloud configurations with identical attributes outside of Always Reconnect. Verified that Always Reconnect only has unique behavior when Instances on EC2 Fleet reboot. Jenkins restart will always reconnect to EC2 Fleet regardless of whether Always Reconnect is included in configuration. Nodes will stay offline if instance is rebooted and Always Reconnect is not selected.

<img width="409" alt="image" src="https://github.com/jenkinsci/ec2-fleet-plugin/assets/38046649/0924ba27-b5f4-4c8a-b0bf-963e97bdea82">

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-08-07 18:49 UTC, pdk27 requested changes
LGTM! 
Can [this](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/docs/CONFIGURATION-AS-CODE.md?plain=1#L21) be updated too?

2023-08-07 20:17 UTC, vineeth-bandi commented
> LGTM! Can [this](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/docs/CONFIGURATION-AS-CODE.md?plain=1#L21) be updated too?

Fixed.

2023-08-12 15:49 UTC, decoursin commented
Always Reconnect seems like by default it should be checked. I don't believe it is currently.

Thanks so much for the PR, I'll check it now that I understand what it does haha :)

2023-08-23 21:32 UTC, pdk27 approved these changes

2023-08-23 21:32 UTC, merged